"""Browns tracking analysis package."""

from .config import (
    BrownsTrackingConfig,
    PathSettings,
    ProjectPaths,
    clear_project_path_cache,
    default_project_config,
    default_project_paths,
    find_project_root,
    resolve_data_file,
    resolve_output_dir,
)
from .constants import (
    EXPECTED_DT_SECONDS,
    EXPECTED_SAMPLE_HZ,
    YARDS_PER_SECOND_TO_MPH,
    YARDS_PER_SECOND_SQ_TO_M_PER_SECOND_SQ,
)
from .metrics import (
    PeakDemandConfig,
    SpeedBand,
    compute_peak_demand_timeseries,
    default_absolute_speed_bands,
    peak_distance_table,
    relative_speed_bands,
    session_extrema_table,
    summarize_speed_bands,
    top_non_overlapping_windows,
)
from .pipeline import (
    annotate_tracking_continuity,
    build_validation_takeaways,
    classify_hsr_exposure,
    compute_data_quality_summary,
    compute_session_event_counts,
    compute_validation_gates,
    load_tracking_data,
    split_early_late_summary,
    summarize_window_context,
    summarize_session,
)
from .presets import PerformanceModelPreset, preferred_performance_model
from .results_contract import (
    SessionAnalysisResults,
    build_peak_window_table,
    build_session_structure_map_table,
    load_results_contract,
    run_session_analysis,
    write_results_contract,
    write_results_tables,
)
from .segmentation import (
    SegmentationConfig,
    build_coach_phase_summary,
    detect_segments,
    summarize_segments,
)

__all__ = [
    "ProjectPaths",
    "BrownsTrackingConfig",
    "PathSettings",
    "EXPECTED_DT_SECONDS",
    "EXPECTED_SAMPLE_HZ",
    "YARDS_PER_SECOND_TO_MPH",
    "YARDS_PER_SECOND_SQ_TO_M_PER_SECOND_SQ",
    "PeakDemandConfig",
    "PerformanceModelPreset",
    "SegmentationConfig",
    "SpeedBand",
    "clear_project_path_cache",
    "compute_peak_demand_timeseries",
    "compute_data_quality_summary",
    "compute_session_event_counts",
    "compute_validation_gates",
    "annotate_tracking_continuity",
    "build_validation_takeaways",
    "classify_hsr_exposure",
    "default_project_config",
    "default_project_paths",
    "default_absolute_speed_bands",
    "detect_segments",
    "find_project_root",
    "load_tracking_data",
    "peak_distance_table",
    "preferred_performance_model",
    "SessionAnalysisResults",
    "run_session_analysis",
    "build_peak_window_table",
    "build_session_structure_map_table",
    "write_results_tables",
    "write_results_contract",
    "load_results_contract",
    "relative_speed_bands",
    "resolve_data_file",
    "resolve_output_dir",
    "session_extrema_table",
    "split_early_late_summary",
    "summarize_window_context",
    "build_coach_phase_summary",
    "summarize_segments",
    "summarize_session",
    "summarize_speed_bands",
    "top_non_overlapping_windows",
]
